# escape=`

FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022

RUN `
  mkdir tmp && mkdir git`
	&& curl -sSfLo tmp/file.zip https://github.com/git-for-windows/git/releases/download/v2.35.1.windows.2/MinGit-2.35.1.2-64-bit.zip `
  && tar -C c:\git -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

RUN `
  mkdir tmp`
  && curl -sSfLo tmp/file.zip https://github.com/git-lfs/git-lfs/releases/download/v3.1.2/git-lfs-windows-amd64-v3.1.2.zip `
  && tar -C c:\git\usr\bin -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

ADD windows/* /bin/

# https://github.com/PowerShell/PowerShell/issues/6211#issuecomment-367477137
USER ContainerAdministrator
RUN setx /M PATH "%PATH%;C:\Program Files\PowerShell"

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
CMD [ "pwsh", "C:\\bin\\clone.ps1" ]
